/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_subbst_permissionsfix_core_PosixFilePermissions */

#ifndef _Included_com_subbst_permissionsfix_core_PosixFilePermissions
#define _Included_com_subbst_permissionsfix_core_PosixFilePermissions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_subbst_permissionsfix_core_PosixFilePermissions
 * Method:    get
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_com_subbst_permissionsfix_core_PosixFilePermissions_get
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_subbst_permissionsfix_core_PosixFilePermissions
 * Method:    set
 * Signature: (Ljava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_com_subbst_permissionsfix_core_PosixFilePermissions_set
  (JNIEnv *, jclass, jstring, jintArray);

#ifdef __cplusplus
}
#endif
#endif
