/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_subbst_permissionsfix_core_PosixFilePermissions */

#ifndef _Included_com_subbst_permissionsfix_core_PosixFilePermissions
#define _Included_com_subbst_permissionsfix_core_PosixFilePermissions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_subbst_permissionsfix_core_PosixFilePermissions
 * Method:    get
 * Signature: (Ljava/io/File;)Ljava/util/Set;
 */
JNIEXPORT jobject JNICALL Java_com_subbst_permissionsfix_core_PosixFilePermissions_get
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_subbst_permissionsfix_core_PosixFilePermissions
 * Method:    set
 * Signature: (Ljava/io/File;Ljava/util/Set;)V
 */
JNIEXPORT void JNICALL Java_com_subbst_permissionsfix_core_PosixFilePermissions_set
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
